### ISSUE TITLE
No = makes me :(

### ISSUE THREAD

**Issue by jtrussell** [dwijesinghe/viMax#1]
I see where you're going with [L29-32](https://github.com/dwijesinghe/viMax/blob/master/plugin/viMax.vim#L29-L32) but the `=` key is super useful and I'm guessing lots of peeps won't be too happy to lose it (for example `gg=G` is a common way to re-indent an entire file). Any thoughts on using Ctrt+/Ctrl-?

**Comment by dwijesinghe** [comment]
@jtrussell Sorry, forgot to respond to this. I initially attempted to make to implement this using Ctrl+/Ctrl- but the binding doesn't seem to work (at least in Windows Gvim). I settled on just using +/- for the time being, although if you are able to get Ctrl+/Ctrl- to work please feel free to send me a pull request. I am also open to other suggestions for the key bindings (and users are welcome to change them for personal use).
